# Generated by Django 4.2.6 on 2025-01-31 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caloriecraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('user_nickname', models.CharField(max_length=50, unique=True, verbose_name='ユーザネーム')),
                ('email', models.CharField(max_length=254, verbose_name='メールアドレス')),
                ('sex', models.IntegerField(verbose_name='性別')),
                ('birthday', models.DateField(null=True, verbose_name='生年月日')),
                ('password', models.CharField(max_length=30, verbose_name='パスワード')),
                ('tell_number', models.CharField(max_length=21, null=True, verbose_name='電話番号')),
            ],
            options={
                'db_table': '01_user',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_name', models.CharField(max_length=25, verbose_name='レシピ名')),
                ('step', models.CharField(max_length=255, verbose_name='手順')),
                ('recipe_id', models.AutoField(primary_key=True, serialize=False, verbose_name='レシピID')),
                ('creator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriecraft.user', verbose_name='レシピ名')),
            ],
            options={
                'db_table': '03_recipes',
            },
        ),
    ]
